--
-- PostgreSQL database dump
--


-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activity_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activity_events (
    id bigint NOT NULL,
    chore_id bigint,
    chore_title character varying(150) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    type character varying(40) NOT NULL,
    actor_user_id bigint NOT NULL,
    group_id bigint NOT NULL,
    CONSTRAINT activity_events_type_check CHECK (((type)::text = ANY ((ARRAY['CHORE_CREATED'::character varying, 'CHORE_COMPLETED'::character varying])::text[])))
);


--
-- Name: activity_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.activity_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chore_completion_dates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chore_completion_dates (
    chore_id bigint NOT NULL,
    completion_date date NOT NULL
);


--
-- Name: chore_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chore_groups (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(500),
    name character varying(100) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    owner_id bigint NOT NULL,
    invite_code character varying(12)
);


--
-- Name: chore_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chore_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chore_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chore_recurrence_days; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chore_recurrence_days (
    chore_id bigint NOT NULL,
    day_of_week character varying(12) NOT NULL,
    CONSTRAINT chore_recurrence_days_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);


--
-- Name: chores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chores (
    id bigint NOT NULL,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(500),
    due_date timestamp(6) with time zone,
    points integer NOT NULL,
    status character varying(20) NOT NULL,
    title character varying(150) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    assigned_user_id bigint,
    created_by bigint NOT NULL,
    group_id bigint NOT NULL,
    icon character varying(16) DEFAULT '🧹'::character varying NOT NULL,
    recurring boolean DEFAULT false NOT NULL,
    recurrence_start_date date,
    CONSTRAINT chores_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying])::text[])))
);


--
-- Name: chores_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: group_memberships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_memberships (
    id bigint NOT NULL,
    joined_at timestamp(6) with time zone NOT NULL,
    role character varying(20) NOT NULL,
    group_id bigint NOT NULL,
    user_id bigint NOT NULL,
    display_title character varying(40),
    CONSTRAINT group_memberships_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'ADMIN'::character varying, 'MEMBER'::character varying])::text[])))
);


--
-- Name: group_memberships_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.group_memberships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_memberships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reward_redemptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reward_redemptions (
    id bigint NOT NULL,
    cost_snapshot integer NOT NULL,
    redeemed_at timestamp(6) with time zone NOT NULL,
    reward_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: reward_redemptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reward_redemptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reward_redemptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rewards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rewards (
    id bigint NOT NULL,
    active boolean NOT NULL,
    cost integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(300),
    name character varying(100) NOT NULL,
    created_by bigint NOT NULL,
    group_id bigint NOT NULL
);


--
-- Name: rewards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rewards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rewards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    avatar_key character varying(32)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: activity_events activity_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_events
    ADD CONSTRAINT activity_events_pkey PRIMARY KEY (id);


--
-- Name: chore_completion_dates chore_completion_dates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chore_completion_dates
    ADD CONSTRAINT chore_completion_dates_pkey PRIMARY KEY (chore_id, completion_date);


--
-- Name: chore_groups chore_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chore_groups
    ADD CONSTRAINT chore_groups_pkey PRIMARY KEY (id);


--
-- Name: chore_recurrence_days chore_recurrence_days_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chore_recurrence_days
    ADD CONSTRAINT chore_recurrence_days_pkey PRIMARY KEY (chore_id, day_of_week);


--
-- Name: chores chores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chores
    ADD CONSTRAINT chores_pkey PRIMARY KEY (id);


--
-- Name: group_memberships group_memberships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_memberships
    ADD CONSTRAINT group_memberships_pkey PRIMARY KEY (id);


--
-- Name: reward_redemptions reward_redemptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reward_redemptions
    ADD CONSTRAINT reward_redemptions_pkey PRIMARY KEY (id);


--
-- Name: rewards rewards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rewards
    ADD CONSTRAINT rewards_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: group_memberships uk_group_membership_user_group; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_memberships
    ADD CONSTRAINT uk_group_membership_user_group UNIQUE (user_id, group_id);


--
-- Name: chore_groups ukaosfogg7o3scao13ndjr9llwi; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chore_groups
    ADD CONSTRAINT ukaosfogg7o3scao13ndjr9llwi UNIQUE (invite_code);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: activity_events fk16n8we5hepbfjrkb2s2u1fkqm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_events
    ADD CONSTRAINT fk16n8we5hepbfjrkb2s2u1fkqm FOREIGN KEY (actor_user_id) REFERENCES public.users(id);


--
-- Name: reward_redemptions fk1fl7vw3n1k600ewfdmcaoau12; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reward_redemptions
    ADD CONSTRAINT fk1fl7vw3n1k600ewfdmcaoau12 FOREIGN KEY (reward_id) REFERENCES public.rewards(id);


--
-- Name: rewards fk5ml6mqt5bukx36oiw65e3sajx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rewards
    ADD CONSTRAINT fk5ml6mqt5bukx36oiw65e3sajx FOREIGN KEY (group_id) REFERENCES public.chore_groups(id);


--
-- Name: chores fk63bske927rd202axivqlj1ovc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chores
    ADD CONSTRAINT fk63bske927rd202axivqlj1ovc FOREIGN KEY (group_id) REFERENCES public.chore_groups(id);


--
-- Name: reward_redemptions fk7mlsj71t0guywfoblp1o3q56a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reward_redemptions
    ADD CONSTRAINT fk7mlsj71t0guywfoblp1o3q56a FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: chore_recurrence_days fkd5vohngo8226p02bl0i960swn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chore_recurrence_days
    ADD CONSTRAINT fkd5vohngo8226p02bl0i960swn FOREIGN KEY (chore_id) REFERENCES public.chores(id);


--
-- Name: chores fke0b3puby4gpup2psqrhbxel0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chores
    ADD CONSTRAINT fke0b3puby4gpup2psqrhbxel0 FOREIGN KEY (assigned_user_id) REFERENCES public.users(id);


--
-- Name: chores fkeonrbka2vwvl5ia30yh7xi3rc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chores
    ADD CONSTRAINT fkeonrbka2vwvl5ia30yh7xi3rc FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: activity_events fkfkhiqm6tnkwmco68681evya1a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_events
    ADD CONSTRAINT fkfkhiqm6tnkwmco68681evya1a FOREIGN KEY (group_id) REFERENCES public.chore_groups(id);


--
-- Name: rewards fkhqksxss7am94arjrdym1mdep2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rewards
    ADD CONSTRAINT fkhqksxss7am94arjrdym1mdep2 FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: chore_groups fkirkyhajwj4q6h93bqgjv5dho9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chore_groups
    ADD CONSTRAINT fkirkyhajwj4q6h93bqgjv5dho9 FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- Name: group_memberships fklq7o99bv8w6paut0ih5yhboia; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_memberships
    ADD CONSTRAINT fklq7o99bv8w6paut0ih5yhboia FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: chore_completion_dates fko0ai1vfu08iln6vvbjd9e6fig; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chore_completion_dates
    ADD CONSTRAINT fko0ai1vfu08iln6vvbjd9e6fig FOREIGN KEY (chore_id) REFERENCES public.chores(id);


--
-- Name: group_memberships fkpy7195afsx40se9y93ltloyea; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_memberships
    ADD CONSTRAINT fkpy7195afsx40se9y93ltloyea FOREIGN KEY (group_id) REFERENCES public.chore_groups(id);


--
-- PostgreSQL database dump complete
--


