CREATE TABLE group_join_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    group_id BIGINT NOT NULL REFERENCES chore_groups(id),
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_group_join_request_user_group UNIQUE (user_id, group_id)
);

CREATE INDEX idx_group_join_requests_group_id ON group_join_requests(group_id);
